#!/usr/bin/env bash
THIS_DIR=$(cd $(dirname $0); pwd)
install() {
echo -e "\033[0;36m"
echo -e "~ Welcome To Source LOST - اهلا بك في سورس لوست ~"
echo -e "--------------------------------------------"
echo -e "|          
echo -e "|                                          |"
echo -e "|           > CH › @F5z123              |"
echo -e "|        ~> DEVELOPER › @z7cz9       |"
echo -e "|                  - LOST -               |"
echo -e "--------------------------------------------"
echo -e "     ~ { Start downloading offices - بدء تنزيل المكاتب } ~"
echo -e "\033[0m"
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y
sudo apt-get install upstart-sysv -y
sudo apt-get install tmux -y
sudo apt-get install dnsutils -y
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
echo -e "\033[0;36m"
echo -e " 25% of offices have been downloaded - تم تنزيل 25% من المكاتب"
echo -e "\033[0m"
if [ "$Version" == "18" ]; then
cd /lib/x86_64-linux-gnu/ && sudo ln -s libreadline.so.7.0 libreadline.so.6
wget "th3boss.com/installubuntu18/compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb" && sudo dpkg -i compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
rm compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
cd 
fi
sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y wget -y
sudo apt-get install screen -y
sudo apt-get install libconfig++9v5 -y 
sudo apt-get install libstdc++6 -y
sudo apt-get install lua-lgi -y
sudo apt-get install libnotify-dev -y
sudo apt-get install lua-space -y
sudo service redis-server start
echo -e "\033[0;36m"
echo -e " 50% of offices have been downloaded - تم تنزيل 50% من المكاتب"
echo -e "\033[0m"
sudo apt-get update -y
sudo apt-get install g++-4.7 -y c++-4.7
sudo apt-get install luarocks -y
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && ./configure && make && sudo make install
sudo luarocks install luasocket
echo -e "\033[0;36m"
echo -e " 75% of offices have been downloaded - تم تنزيل 75% من المكاتب"
echo -e "\033[0m"
sudo luarocks install luasec
sudo luarocks install redis-lua
sudo luarocks install lua-term
sudo luarocks install serpent
sudo luarocks install dkjson
sudo luarocks install Lua-cURL
sudo luarocks install luautf8
echo -e "\033[0;36m"
echo -e "~ Welcome To Source LOST - اهلا بك في سورس لوست ~"
echo -e "--------------------------------------------"
echo -e "|          
echo -e "|                                          |"
echo -e "|           > CH › @F5z123              |"
echo -e "|        ~> DEVELOPER › @z7cz9       |"
echo -e "|                  - LOST -               |"
echo -e "--------------------------------------------"
echo -e "~ { Office download and installation completed - تم اكتمال تنزيل وتثبيت المكاتب } ~"
echo -e "\033[0m"
cd .. ;sudo rm -rf luarocks*
sudo timedatectl set-timezone Asia/Baghdad
cd $THIS_DIR && sudo chmod +x tg
lua LOST.lua
}
if [ "$1" = "install" ]; then
install
else
if [ ! -f ./tg ]; then
echo "Tg Is Not Found"
exit 1
fi
cd $THIS_DIR && sudo chmod +x tg
lua LOST.lua
fi
